baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'True Mission Outreach South America'
[module]
proxy = "direct"
[module.hugoVersion]
extended = true
min = "0.73.0"
[[module.imports]]
path = "github.com/google/docsy"
disable = false
[[module.imports]]
path = "github.com/google/docsy/dependencies"
disable = false
[params]
copyright = "True Mission Outreach"
navbar_logo = false